### ISSUE TITLE
Support for the new Argon2 hashing function

### ISSUE THREAD

**Issue by rvangraan** [potatosalad/erlang-libsodium#6]
Hi there,

Can you tell me how I'd go about adding support for these functions? https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html

The upstream libsodium seems to have removed the scrypt functions :(

Thanks!

**Comment by potatosalad** [comment]
@rvangraan ...several years later...

As of [libsodium 1.0.18](https://hex.pm/packages/libsodium/1.0.18), you can use any of the following:

* [`crypto_pwhash_argon2i`](https://hexdocs.pm/libsodium/libsodium_crypto_pwhash_argon2i.html)
* [`crypto_pwhash_argon2id`](https://hexdocs.pm/libsodium/libsodium_crypto_pwhash_argon2id.html)
* [`crypto_pwhash_scryptsalsa208sha256`](https://hexdocs.pm/libsodium/libsodium_crypto_pwhash_scryptsalsa208sha256.html)
